apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secrets
  namespace: bigdata
type: Opaque
stringData:
  MONGODB_BACKUP_PASSWORD: "123456"
  MONGODB_CLUSTER_ADMIN_PASSWORD: "123456"
  MONGODB_CLUSTER_MONITOR_PASSWORD: "123456"
  MONGODB_USER_ADMIN_PASSWORD: "123456"
  MONGODB_BIGDATA_USER: "spark-user"
  MONGODB_BIGDATA_PASSWORD: "spark-pass"
  # Thêm keyfile ngẫu nhiên. Thay <CHUỖI_NGẪU_NHIÊN_DÀI> bằng chuỗi bạn tạo
  MONGODB_KEYFILE: "+00RrjM/6yU0mZQyLmliQhO4/Mhkl/pMBLyxRzFOIWRlWWMhq27pu8B/w2ttWuVXvbkIsS9hQlBJKSfbx/aXWEBXkdalSRWKsXrJKuGPYjKM4DEVs1bjQ5jwIgoaDMWXBmu7Vo/fP7ppTYP5vOagFB2gmLtBXm6mIkP22MWdVIyRAY4aOxskd1KIRSvIy4JjZmCobsKgoMjE7IsNKa5ccwXuiN7YpxiMA6utuj6VuiUa1ZqGehhJ+hT7p9Uzj8LM2/gCkS4cnH9v7RqDn6OaHmY6OxG6tFc4M9eqDc1onShJItTUJYFkXtgHbGhjEEQRJnvkBQJc63rEA763yeRyLB2Lf2dNuTeDHVkAE0Y5yfjOULUEr6dwkcF57y4IbmtruhQT5188m5Sb7O7S757Y9xLyZ3AlnDOIhqgd9V8JxkWHdoP1L4f1VoPVoSYuFC4uDVGragJk7ePl+7TzD1t1iy0MtoQ1dRdFScmtzCqmtnrpzHKp55CGjXvtofkhrptELDZpZnUTuwHTtOFVTdxUWhofU1ye2qgWXIBzDOSqmojFQ+drySB2J8gkdZXjQGUQwVP79LQEhDQUmainxBs1g2qsWGp6Hutxr4EcfISRNTgFuABCjtO86bG+Wv2KNY57p1y3CfrXpm324nkar8ILSHdzSaFVUilaLBtFRYEbW2DIt689pZNLXS2C/bJKOhm0SHR2XhnAVDVYusiiZRkeGmkOpLQKDm7k+zR24tkiTp/q5ojfy3dbRjl+dJop+OiPb/n/V6jrW0Hqi8iidnu+3+3DaKB3IVygqENZN9BcIL+8e/TMUD67qg9/X1HerlW2Iil4++9wJU+G4lI/d/CybzDuNp1DXql8MLC/vftIxJ7/YUBB0VqKw3nZruGGxEFAVe407jsC6lXbGUNemSvMwj070KU6VK7KwhaPITRitm8y3nUicW2IKAezeFzAvbF8glqHyDPJnLr1n5B2yi14WrxTg+jdu79RYua9vRSwTwphZPaz"